name: Lint Yaml

# **What it does**: This lints our yaml files in the docs repository.
# **Why we have it**: We want some level of consistent formatting for YAML files.
# **Who does it impact**: Docs engineering, docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.yml"
      - "**/*.yaml"
  pull_request:
    paths:
      - "**/*.yml"
      - "**/*.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          CACHE_NAME: npm-cache-dependencies
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_NAME }}-

      - name: Install dependencies
        shell: bash
        run: |
          npm ci

      - name: Run linter
        run: npx --no-install prettier -c "**/*.{yml,yaml}"
